[package]
name = "generic-btree"
version = "0.1.0"
edition = "2018"

[features]
default = ["dot"]
dot = []

[dependencies]
slab = "*"
cc-traits = { version = "^0.4", features = ["nightly", "slab"] }

staticvec = "^0.10"

[dev-dependencies]
rand = { version = "^0.7", features = ["small_rng"] }
